name: UnlimitedFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.0
description: Plugin for the UnlimitedFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, tylerhyperHD, AwesomePinch]

# plugin.yml is no longer used to define commands.
