name: PacksFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: The all op managment system for PacksFreedom
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI, Votifier]
authors: [Madgeek1450, Prozza, xPacks]
